export function asset(path) {
  return `${import.meta.env.BASE_URL}${String(path).replace(/^\//, "")}`;
}

export const categories = [
  {
    slug: "laptops",
    label: "Laptops",
    children: [
      "Everyday Use Notebooks",
      "MSI Workstation Series",
      "MSI Prestige Series",
      "Gaming Notebooks",
      "Tablets And Pads",
      "Netbooks",
      "Infinity Gaming Notebooks",
    ],
    series: [
      { name: "MSI WS Series", count: 12 },
      { name: "MSI WT Series", count: 31 },
      { name: "MSI WE Series", count: 7 },
    ],
  },
  {
    slug: "desktops",
    label: "Desktop PCs",
    children: ["Custom PCs", "Servers", "MSI All-In-One PCs", "HP/Compaq PCs", "ASUS PCs", "Tecs PCs"],
    series: [
      { name: "MSI Infinite Series", count: 8 },
      { name: "MSI Trident", count: 14 },
      { name: "MSI Nightblade", count: 6 },
    ],
  },
  { slug: "networking", label: "Networking Devices", children: ["Routers", "Switches", "Mesh Wi-Fi"] },
  { slug: "printers", label: "Printers & Scanners", children: ["Laser", "Inkjet", "Scanners"] },
  {
    slug: "parts",
    label: "PC Parts",
    children: [
      "CPUS",
      "Add On Cards",
      "Hard Drives (Internal)",
      "Graphic Cards",
      "Keyboards / Mice",
      "Cases / Power Supplies / Cooling",
      "RAM (Memory)",
      "Software",
      "Speakers / Headsets",
      "Motherboards",
    ],
  },
  { slug: "other", label: "All Other Products", children: ["Accessories", "Cables", "Storage"] },
  { slug: "repairs", label: "Repairs", children: [] },
];

const imgs = [
  "img/products/p6.jpg",
  "img/products/p11.jpg",
  "img/products/p12.jpg",
  "img/products/p13.jpg",
  "img/products/p14.jpg",
  "img/products/p15.jpg",
  "img/product-main.jpg",
  "img/product-alt.jpg",
].map(asset);

export const products = [
  {
    id: "msi-pro-16",
    sku: "D5515AI",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-One",
    short: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    price: 499,
    oldPrice: 499,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[0],
    images: [imgs[0], imgs[1], imgs[2], asset("img/product-main.jpg")],
    tags: ["new", "custom"],
  },
  {
    id: "msi-creator-17",
    sku: "D5515AI",
    title: "MSI CREATOR 17 A10SFS-240AU 17 UHD 4K HDR Thin Bezel Intel 10th Gen i7 10875H - RTX 2070 SUPER MAX Q - 16GB RAM - 1TB SSD NVME - Windows 10 PRO Laptop",
    short: "MSI CREATOR 17 A10SFS-240AU 17 UHD 4K HDR Thin Bezel...",
    price: 499,
    oldPrice: 599,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[1],
    images: [imgs[1], imgs[2], imgs[3]],
    tags: ["new"],
  },
  {
    id: "msi-trident-3",
    sku: "D5515AI",
    title: "MSI MPG Trident 3",
    short: "MSI MPG Trident 3 10SC-005AU Intel i7 10700F, 2060 SUPER, 16GB RAM, 512GB SSD, 2TB HDD, Windows 10 Home, Gaming Keyboard and Mouse 3 Years Warranty Gaming Desktop",
    price: 3299,
    oldPrice: 3799,
    inStock: true,
    reviews: 0,
    rating: 0,
    category: "desktops",
    brand: "MSI",
    color: "WHITE",
    image: imgs[6],
    images: [imgs[6], imgs[7], imgs[4], imgs[5]],
    featured: true,
    tags: ["msi-desktop", "custom"],
    bullets: [
      "Intel Core i7-10700F",
      "Intel H410",
      "WHITE",
      "NVIDIA MSI GeForce RTX 2060 SUPER 8GB AERO ITX GDDR6",
      "SO-DIMM 16GB (16GB x 1) DDR4 2666MHz",
      "2 total slots (64GB Max)",
      "512GB (1 x 512GB) M.2 NVMe PCIe GEN3x4 SSD 2TB (2.5) 5400RPM",
      "Gaming Keyboard GK30 + Gaming Mouse GM11",
      "3.5 HDD (0/0), 2.5 HDD/SSD(1/0), M.2 (1/0)",
      "Intel WGI219Vethernet (10/100/1000M)",
      "AX200 (WIFI 6)+BT5.1",
      "PSU 330W",
      "Fan Cooler",
    ],
  },
  {
    id: "msi-trident-x",
    sku: "D8821TR",
    title: "MSI MEG Trident X 10SD-1012AU Intel i7 10700K, 2070 SUPER, 32GB RAM, 1TB SSD, Windows 10 Home, Gaming Keyboard and Mouse 3 Years Warranty",
    short: "MSI MEG Trident X 10SD-1012AU Intel i7 10700K, 2070 SUPER...",
    price: 4349,
    oldPrice: 4799,
    inStock: true,
    reviews: 4,
    rating: 5,
    category: "desktops",
    brand: "MSI",
    color: "Black",
    image: imgs[5],
    images: [imgs[5], imgs[6], imgs[7]],
    tags: ["custom", "msi-desktop"],
  },
  {
    id: "msi-gs-66",
    sku: "GS66-01",
    title: "MSI GS Series 15.6\" Gaming Laptop RTX 2070",
    short: "MSI GS Series 15.6 Gaming Laptop RTX 2070",
    price: 1899,
    oldPrice: 2199,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[2],
    images: [imgs[2], imgs[0]],
    tags: ["new", "msi-laptop"],
  },
  {
    id: "msi-gt-76",
    sku: "GT76-01",
    title: "MSI GT Series Titan Gaming Notebook",
    short: "MSI GT Series Titan Gaming Notebook",
    price: 2499,
    oldPrice: 2799,
    inStock: false,
    reviews: 4,
    rating: 5,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[3],
    images: [imgs[3], imgs[1]],
    tags: ["msi-laptop"],
  },
  {
    id: "msi-gl-65",
    sku: "GL65-01",
    title: "MSI GL Series Leopard 15.6\" 144Hz",
    short: "MSI GL Series Leopard 15.6 144Hz",
    price: 1299,
    oldPrice: 1499,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[0],
    images: [imgs[0], imgs[2]],
    tags: ["msi-laptop", "new"],
  },
  {
    id: "msi-ge-66",
    sku: "GE66-01",
    title: "MSI GE Series Raider RGB Gaming Laptop",
    short: "MSI GE Series Raider RGB Gaming Laptop",
    price: 2099,
    oldPrice: 2399,
    inStock: true,
    reviews: 4,
    rating: 5,
    category: "laptops",
    brand: "MSI",
    color: "Black",
    image: imgs[1],
    images: [imgs[1], imgs[3]],
    tags: ["msi-laptop"],
  },
  {
    id: "msi-infinite",
    sku: "INF-01",
    title: "MSI Infinite Series Gaming Desktop",
    short: "MSI Infinite Series Gaming Desktop",
    price: 1599,
    oldPrice: 1799,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "desktops",
    brand: "MSI",
    color: "Black",
    image: imgs[4],
    images: [imgs[4], imgs[0]],
    tags: ["msi-desktop", "custom"],
  },
  {
    id: "msi-nightblade",
    sku: "NB-01",
    title: "MSI Nightblade Compact Gaming PC",
    short: "MSI Nightblade Compact Gaming PC",
    price: 1399,
    oldPrice: 1599,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "desktops",
    brand: "MSI",
    color: "Black",
    image: imgs[5],
    images: [imgs[5], imgs[1]],
    tags: ["msi-desktop"],
  },
  {
    id: "bravo-v6",
    sku: "BRV-6",
    title: "Custom Build Bravo V6",
    short: "Custom Build Bravo V6",
    price: 2199,
    oldPrice: 2499,
    inStock: true,
    reviews: 4,
    rating: 5,
    category: "desktops",
    brand: "Tecs",
    color: "Black",
    image: imgs[6],
    images: [imgs[6], imgs[2]],
    tags: ["custom", "new"],
  },
  {
    id: "alpha-v6",
    sku: "ALP-6",
    title: "Custom Build Alpha V6",
    short: "Custom Build Alpha V6",
    price: 1899,
    oldPrice: 2099,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "desktops",
    brand: "Tecs",
    color: "White",
    image: imgs[7],
    images: [imgs[7], imgs[3]],
    tags: ["custom"],
  },
  {
    id: "monitor-mag",
    sku: "MAG-27",
    title: "MSI MAG 27\" 144Hz Gaming Monitor",
    short: "MSI MAG 27 144Hz Gaming Monitor",
    price: 349,
    oldPrice: 429,
    inStock: true,
    reviews: 4,
    rating: 5,
    category: "other",
    brand: "MSI",
    color: "Black",
    image: imgs[2],
    images: [imgs[2], imgs[3]],
    tags: ["monitor", "new"],
  },
  {
    id: "monitor-optix",
    sku: "OPT-32",
    title: "MSI Optix 32\" Curved 165Hz Monitor",
    short: "MSI Optix 32 Curved 165Hz Monitor",
    price: 499,
    oldPrice: 599,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "other",
    brand: "MSI",
    color: "Black",
    image: imgs[3],
    images: [imgs[3], imgs[4]],
    tags: ["monitor"],
  },
  {
    id: "hp-aio",
    sku: "HP-AIO",
    title: "HP All-In-One 24\" Home Desktop",
    short: "HP All-In-One 24 Home Desktop",
    price: 899,
    oldPrice: 999,
    inStock: true,
    reviews: 4,
    rating: 4,
    category: "desktops",
    brand: "HP",
    color: "Silver",
    image: imgs[4],
    images: [imgs[4], imgs[0]],
    tags: ["new"],
  },
  {
    id: "asus-rog",
    sku: "ROG-01",
    title: "ASUS ROG Strix Gaming Desktop",
    short: "ASUS ROG Strix Gaming Desktop",
    price: 1799,
    oldPrice: 1999,
    inStock: false,
    reviews: 4,
    rating: 5,
    category: "desktops",
    brand: "ASUS",
    color: "Black",
    image: imgs[5],
    images: [imgs[5], imgs[1]],
    tags: ["custom"],
  },
];

for (let i = 0; i < 20; i++) {
  const base = products[i % 8];
  products.push({
    ...base,
    id: `${base.id}-x${i + 1}`,
    sku: `${base.sku}-${i + 1}`,
    title: base.title,
    image: imgs[i % imgs.length],
    images: [imgs[i % imgs.length], imgs[(i + 3) % imgs.length]],
    price: base.price,
    inStock: i % 5 !== 2,
  });
}

export const news = [
  {
    date: "01.09.2020",
    image: asset("img/insta/i3.jpg"),
    text: "If you’ve recently made a desktop PC or laptop purchase, you might want to consider adding peripherals to enhance your home office setup, your gaming rig, or your business workspace...",
  },
  {
    date: "01.09.2020",
    image: asset("img/insta/i4.jpg"),
    text: "As a gamer, superior sound counts for a lot. You need to hear enemies tiptoeing up behind you for a sneak attack or a slight change in the atmospheric music signaling a new challenge or task...",
  },
  {
    date: "01.09.2020",
    image: asset("img/insta/i6.jpg"),
    text: "If you’ve recently made a desktop PC or laptop purchase, you might want to consider adding peripherals to enhance your home office setup, your gaming rig, or your business workspace...",
  },
];

export const instagram = [
  "img/insta/i2.jpg",
  "img/insta/i3.jpg",
  "img/insta/i4.jpg",
  "img/insta/i6.jpg",
  "img/insta/i8.jpg",
  "img/products/p11.jpg",
  "img/products/p12.jpg",
  "img/products/p13.jpg",
  "img/products/p14.jpg",
].map(asset);

export const brands = ["MSI", "Razer", "Thermaltake", "Adata", "Hewlett Packard", "Gigabyte"];

export const priceBuckets = [
  [0, 1000],
  [1000, 2000],
  [2000, 3000],
  [3000, 4000],
  [4000, 5000],
  [5000, 6000],
  [6000, 7000],
  [7000, Infinity],
];

export const heroSlides = [
  {
    image: asset("img/hero-3.jpg"),
    tag: "EOFY DEAL",
    title: "SCORE A BONUS GAMING MONITOR",
    subtitle: "WHEN YOU BUY ANY SELECTED MSI GAMING DESKTOP",
    note: "VALID FROM MAY 12 — SEP 7, 2020 OR WHILE STOCKS LAST.",
  },
  {
    image: asset("img/product-main.jpg"),
    tag: "NEW ARRIVAL",
    title: "CUSTOM BUILDS, READY TO PLAY",
    subtitle: "OWN IT NOW, UP TO 6 MONTHS INTEREST FREE",
    note: "IN STOCK IN OUR MELBOURNE SHOWROOM AND ONLINE.",
  },
  {
    image: asset("img/products/p15.jpg"),
    tag: "GAMING WEEK",
    title: "OUTPLAY THE COMPETITION",
    subtitle: "10TH GEN INTEL CORE + RTX SUPER DESKTOPS",
    note: "FREE KEYBOARD AND MOUSE ON SELECTED MODELS.",
  },
];

export function money(n) {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

export function getProduct(id) {
  return products.find((p) => p.id === id);
}
